logging:
  level:
    root: info
    org.springframework.boot.autoconfigure: warn
    csis3275.project.seasell: debug
jwt:
  secret: ghm5XUtja+0LNWQ2TCOOPlAaABz8atEU8hzDV0RejM5Hsf8SfZQ4cEwJYFZOmd26

storage:
  type: local
  local:
    base-path: ./images
spring:
  sql:
    init:
      mode: always #always initialize database using script even for non-embeded database
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true

