logging:
  level:
    root: info
    org.springframework.boot.autoconfigure: warn
    csis3275.project.seasell: debug
jwt:
  secret: ghm5XUtja+0LNWQ2TCOOPlAaABz8atEU8hzDV0RejM5Hsf8SfZQ4cEwJYFZOmd26

storage:
  type: local
  local:
    base-path: ./images
spring:
  sql:
    init:
      mode: always #always initialize database using script even for non-embeded database
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/seasell
    username: mysql
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver

